apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
spec:
  selector:
    matchLabels:
      app: nginx
  replicas: 1
  template:
    metadata:
      labels:
        app: nginx
    spec:
      initContainers:
      - name: init-myservice
        image: busybox:1.28
        command:
            - /bin/sh
            - -c
            - /opt/scripts/create-db.sh
        volumeMounts:
          - name: create-db
            mountPath: /opt/scripts/create-db.sh
            subPath: create-db.sh
      containers:
      - name: nginx
        image: nginx:1.14.2
        ports:
        - containerPort: 80
      volumes:
        - name: create-db
          configMap:
            name: create-db
            defaultMode: 0755